In [2]:
# Aula 3
# url :  https://dados.gov.br/dataset/ocorrencias-aeronauticas-da-aviacao-civil-brasileira
#     Objetivos:
#     -> Dsenvolvimento
#         1. Extração
#         2. Validação 
#         3. Limpeza
#         4. Trasnformação

In [2]:
import pandas as pd

In [3]:
dataframe = pd.read_csv("ocorrencia.csv", sep=";", parse_dates=['ocorrencia_dia'], dayfirst=True)
dataframe.head(10)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
5,39807,39807,39807,39807,39807,INCIDENTE,***,***,SALVADOR,BA,...,2010-01-06,17:53:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
6,40215,40215,40215,40215,40215,INCIDENTE,***,***,COARI,AM,...,2010-01-07,18:40:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,SIM
7,39707,39707,39707,39707,39707,INCIDENTE GRAVE,-6.5319444444,-64.3805555556,CANUTAMA,AM,...,2010-01-09,12:30:00,SIM,FINALIZADA,IG-028/CENIPA/2011,SIM,2011-07-21,3,1,NÃO
8,39156,39156,39156,39156,39156,INCIDENTE GRAVE,-15.2402777778,-59.3541666667,CASCAVEL,PR,...,2010-01-10,23:15:00,SIM,FINALIZADA,I-004/CENIPA/2011,SIM,2011-06-30,2,1,NÃO
9,39711,39711,39711,39711,39711,INCIDENTE GRAVE,***,***,PARÁ DE MINAS,MG,...,2010-01-10,20:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO

In [5]:
dataframe.loc[1, 'ocorrencia_cidade']

'BELÉM'

In [6]:
dataframe.loc[3]

codigo_ocorrencia                               39527
codigo_ocorrencia1                              39527
codigo_ocorrencia2                              39527
codigo_ocorrencia3                              39527
codigo_ocorrencia4                              39527
ocorrencia_classificacao                     ACIDENTE
ocorrencia_latitude                    -13.1066666667
ocorrencia_longitude                   -55.9930555556
ocorrencia_cidade                  LUCAS DO RIO VERDE
ocorrencia_uf                                      MT
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             ****
ocorrencia_dia                    2010-01-04 00:00:00
ocorrencia_hora                              17:30:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero         A-539/CENIPA/2018
divulgacao_relatorio_publicado                    SIM
divulgacao_dia_publicacao                  2019-10-28
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 3, dtype: object

In [41]:
dataframe.loc[1:3]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO

In [42]:
dataframe.loc[[10,40]]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
10,39789,39789,39789,39789,39789,INCIDENTE,NaN,NaN,SÃO PEDRO DO SUL,RS,...,2010-01-10,21:30:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
40,39158,39158,39158,39158,39158,INCIDENTE,***,***,BELÉM,PA,...,2010-01-28,16:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

In [43]:
dataframe.loc[:,'ocorrencia_cidade']

0           RIO DE JANEIRO
1                    BELÉM
2           RIO DE JANEIRO
3       LUCAS DO RIO VERDE
4                  PELOTAS
               ...
6109                RECIFE
6110           PORTO VELHO
6111                 BELÉM
6112            DOM AQUINO
6113              CAMPINAS
Name: ocorrencia_cidade, Length: 6114, dtype: object

In [44]:
dataframe.codigo_ocorrencia.is_unique

True

In [45]:
dataframe.ocorrencia_uf.is_unique

False

In [46]:
dataframe.set_index('codigo_ocorrencia')

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,,,,,,,
40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80245,80245,80245,80245,80245,INCIDENTE,-8.12638,-34.92277,RECIFE,PE,BRASIL,...,2021-08-15,15:05:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
80247,80247,80247,80247,80247,INCIDENTE,-8.713611111111,-63.90277777777,PORTO VELHO,RO,BRASIL,...,2021-08-16,02:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
80251,80251,80251,80251,80251,INCIDENTE,-1.384722222222,-48.47888888888,BELÉM,PA,BRASIL,...,2021-08-17,15:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
80257,80257,80257,80257,80257,ACIDENTE,-15.430833,-54.699722,DOM AQUINO,MT,BRASIL,...,2021-08-18,16:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
80259,80259,80259,80259,80259,INCIDENTE,-23.00694444444,-47.13444444444,CAMPINAS,SP,BRASIL,...,2021-08-18,12:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [102]:
dataframe.set_index('codigo_ocorrencia', inplace=True)

In [108]:
dataframe.head(10)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,,,,,,,
40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,0,0,1,NÃO
40349,40349,40349,40349,40349,INCIDENTE,0,0,BELÉM,PA,BRASIL,...,2010-01-03,11:05:00,SIM,FINALIZADA,0,NÃO,0,0,1,NÃO
40351,40351,40351,40351,40351,INCIDENTE,0,0,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,03:00:00,SIM,FINALIZADA,0,NÃO,0,0,1,NÃO
39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
40324,40324,40324,40324,40324,INCIDENTE,0,0,PELOTAS,RS,BRASIL,...,2010-01-05,19:25:00,SIM,FINALIZADA,0,NÃO,0,0,1,NÃO
39807,39807,39807,39807,39807,INCIDENTE,***,***,SALVADOR,BA,BRASIL,...,2010-01-06,17:53:00,***,0,0,NÃO,0,0,1,NÃO
40215,40215,40215,40215,40215,INCIDENTE,***,***,COARI,AM,BRASIL,...,2010-01-07,18:40:00,SIM,FINALIZADA,0,NÃO,0,0,1,SIM
39707,39707,39707,39707,39707,INCIDENTE GRAVE,-6.5319444444,-64.3805555556,CANUTAMA,AM,BRASIL,...,2010-01-09,12:30:00,SIM,FINALIZADA,IG-028/CENIPA/2011,SIM,2011-07-21,3,1,NÃO
39156,39156,39156,39156,39156,INCIDENTE GRAVE,-15.2402777778,-59.3541666667,CASCAVEL,PR,BRASIL,...,2010-01-10,23:15:00,SIM,FINALIZADA,I-004/CENIPA/2011,SIM,2011-06-30,2,1,NÃO
39711,39711,39711,39711,39711,INCIDENTE GRAVE,***,***,PARÁ DE MINAS,MG,BRASIL,...,2010-01-10,20:00:00,***,0,0,NÃO,0,0,1,NÃO

In [107]:
dataframe.loc[40211]

codigo_ocorrencia1                              40211
codigo_ocorrencia2                              40211
codigo_ocorrencia3                              40211
codigo_ocorrencia4                              40211
ocorrencia_classificacao                    INCIDENTE
ocorrencia_latitude                               ***
ocorrencia_longitude                              ***
ocorrencia_cidade                      RIO DE JANEIRO
ocorrencia_uf                                      RJ
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                                0
ocorrencia_dia                    2010-01-03 00:00:00
ocorrencia_hora                              12:00:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero                       ***
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                           0
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 40211, dtype: object

In [115]:
dataframe.reset_index(drop=True, inplace=True)

In [51]:
dataframe.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

In [52]:
dataframe.loc[0, 'ocorrencia_aerodromo']

'****'

In [53]:
dataframe.loc[0, 'ocorrencia_aerodromo'] = ''

In [54]:
dataframe.loc[0, 'ocorrencia_aerodromo']

''

In [55]:
dataframe.loc[0]

codigo_ocorrencia1                              40211
codigo_ocorrencia2                              40211
codigo_ocorrencia3                              40211
codigo_ocorrencia4                              40211
ocorrencia_classificacao                    INCIDENTE
ocorrencia_latitude                               ***
ocorrencia_longitude                              ***
ocorrencia_cidade                      RIO DE JANEIRO
ocorrencia_uf                                      RJ
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo
ocorrencia_dia                    2010-01-03 00:00:00
ocorrencia_hora                              12:00:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero                       ***
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                         NaN
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 0, dtype: object

In [56]:
dataframe.loc[1] = 20

In [57]:
dataframe.head(2)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03 00:00:00,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20

In [60]:
dataframe.loc[:,'ocorrencia_latitude'] = 10

In [62]:
dataframe.head(10)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,10,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03 00:00:00,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,20,20,20,20,20,10,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
2,40351,40351,40351,40351,INCIDENTE,10,NaN,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03 00:00:00,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,ACIDENTE,10,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04 00:00:00,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,INCIDENTE,10,NaN,PELOTAS,RS,BRASIL,...,2010-01-05 00:00:00,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
5,39807,39807,39807,39807,INCIDENTE,10,***,SALVADOR,BA,BRASIL,...,2010-01-06 00:00:00,17:53:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
6,40215,40215,40215,40215,INCIDENTE,10,***,COARI,AM,BRASIL,...,2010-01-07 00:00:00,18:40:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,SIM
7,39707,39707,39707,39707,INCIDENTE GRAVE,10,-64.3805555556,CANUTAMA,AM,BRASIL,...,2010-01-09 00:00:00,12:30:00,SIM,FINALIZADA,IG-028/CENIPA/2011,SIM,2011-07-21,3,1,NÃO
8,39156,39156,39156,39156,INCIDENTE GRAVE,10,-59.3541666667,CASCAVEL,PR,BRASIL,...,2010-01-10 00:00:00,23:15:00,SIM,FINALIZADA,I-004/CENIPA/2011,SIM,2011-06-30,2,1,NÃO
9,39711,39711,39711,39711,INCIDENTE GRAVE,10,***,PARÁ DE MINAS,MG,BRASIL,...,2010-01-10 00:00:00,20:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO

In [64]:
dataframe['ocorrencia_uf_bkp'] = dataframe.ocorrencia_uf

In [65]:
dataframe.head(10)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,40211,40211,40211,40211,INCIDENTE,10,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,RJ
1,20,20,20,20,20,10,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
2,40351,40351,40351,40351,INCIDENTE,10,NaN,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,RJ
3,39527,39527,39527,39527,ACIDENTE,10,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO,MT
4,40324,40324,40324,40324,INCIDENTE,10,NaN,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,RS
5,39807,39807,39807,39807,INCIDENTE,10,***,SALVADOR,BA,BRASIL,...,17:53:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,BA
6,40215,40215,40215,40215,INCIDENTE,10,***,COARI,AM,BRASIL,...,18:40:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,SIM,AM
7,39707,39707,39707,39707,INCIDENTE GRAVE,10,-64.3805555556,CANUTAMA,AM,BRASIL,...,12:30:00,SIM,FINALIZADA,IG-028/CENIPA/2011,SIM,2011-07-21,3,1,NÃO,AM
8,39156,39156,39156,39156,INCIDENTE GRAVE,10,-59.3541666667,CASCAVEL,PR,BRASIL,...,23:15:00,SIM,FINALIZADA,I-004/CENIPA/2011,SIM,2011-06-30,2,1,NÃO,PR
9,39711,39711,39711,39711,INCIDENTE GRAVE,10,***,PARÁ DE MINAS,MG,BRASIL,...,20:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,MG

In [66]:
dataframe.loc[dataframe.ocorrencia_uf == 'SP',['ocorrencia_classificacao']] = 'Não há INCIDENTE'

In [67]:
dataframe.loc[dataframe.ocorrencia_uf == 'SP',['ocorrencia_classificacao']]

     ocorrencia_classificacao
11           Não há INCIDENTE
16           Não há INCIDENTE
18           Não há INCIDENTE
26           Não há INCIDENTE
27           Não há INCIDENTE
...                       ...
6084         Não há INCIDENTE
6085         Não há INCIDENTE
6104         Não há INCIDENTE
6108         Não há INCIDENTE
6113         Não há INCIDENTE

[1464 rows x 1 columns]

In [68]:
dataframe.head(10)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,40211,40211,40211,40211,INCIDENTE,10,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,RJ
1,20,20,20,20,20,10,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
2,40351,40351,40351,40351,INCIDENTE,10,NaN,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,RJ
3,39527,39527,39527,39527,ACIDENTE,10,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO,MT
4,40324,40324,40324,40324,INCIDENTE,10,NaN,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,RS
5,39807,39807,39807,39807,INCIDENTE,10,***,SALVADOR,BA,BRASIL,...,17:53:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,BA
6,40215,40215,40215,40215,INCIDENTE,10,***,COARI,AM,BRASIL,...,18:40:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,SIM,AM
7,39707,39707,39707,39707,INCIDENTE GRAVE,10,-64.3805555556,CANUTAMA,AM,BRASIL,...,12:30:00,SIM,FINALIZADA,IG-028/CENIPA/2011,SIM,2011-07-21,3,1,NÃO,AM
8,39156,39156,39156,39156,INCIDENTE GRAVE,10,-59.3541666667,CASCAVEL,PR,BRASIL,...,23:15:00,SIM,FINALIZADA,I-004/CENIPA/2011,SIM,2011-06-30,2,1,NÃO,PR
9,39711,39711,39711,39711,INCIDENTE GRAVE,10,***,PARÁ DE MINAS,MG,BRASIL,...,20:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,MG

In [69]:
dataframe.loc[dataframe.ocorrencia_uf == 'SP']

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
11,40069,40069,40069,40069,Não há INCIDENTE,10,-46.6341666667,SÃO PAULO,SP,BRASIL,...,14:50:00,SIM,FINALIZADA,A-121/CENIPA/2012,SIM,2012-11-19,8,1,NÃO,SP
16,39809,39809,39809,39809,Não há INCIDENTE,10,NaN,SÃO PAULO,SP,BRASIL,...,15:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,SP
18,39828,39828,39828,39828,Não há INCIDENTE,10,***,SANTOS,SP,BRASIL,...,17:45:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,SP
26,39847,39847,39847,39847,Não há INCIDENTE,10,NaN,SOROCABA,SP,BRASIL,...,13:10:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,SP
27,39768,39768,39768,39768,Não há INCIDENTE,10,NaN,CAMPINAS,SP,BRASIL,...,20:45:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6084,80234,80234,80234,80234,Não há INCIDENTE,10,-46.656389,SÃO PAULO,SP,BRASIL,...,13:20:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,SP
6085,80208,80208,80208,80208,Não há INCIDENTE,10,-46.633889,SÃO PAULO,SP,BRASIL,...,19:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,SP
6104,80238,80238,80238,80238,Não há INCIDENTE,10,-50.002500,VOTUPORANGA,SP,BRASIL,...,19:09:00,SIM,ATIVA,***,NÃO,NaN,0,1,NÃO,SP
6108,80244,80244,80244,80244,Não há INCIDENTE,10,-46.537076°,BRAGANÇA PAULISTA,SP,BRASIL,...,15:20:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,SP
6113,80259,80259,80259,80259,Não há INCIDENTE,10,-47.13444444444,CAMPINAS,SP,BRASIL,...,12:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,SP

In [71]:
dataframe

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6109,80245,80245,80245,80245,80245,INCIDENTE,-8.12638,-34.92277,RECIFE,PE,...,2021-08-15,15:05:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6110,80247,80247,80247,80247,80247,INCIDENTE,-8.713611111111,-63.90277777777,PORTO VELHO,RO,...,2021-08-16,02:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6111,80251,80251,80251,80251,80251,INCIDENTE,-1.384722222222,-48.47888888888,BELÉM,PA,...,2021-08-17,15:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6112,80257,80257,80257,80257,80257,ACIDENTE,-15.430833,-54.699722,DOM AQUINO,MT,...,2021-08-18,16:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6113,80259,80259,80259,80259,80259,INCIDENTE,-23.00694444444,-47.13444444444,CAMPINAS,SP,...,2021-08-18,12:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [73]:

# ocorrencia_uf
# **
# ocorrencia_aerodromo
# ###!
# ####
# ****
# *****
# ocorrencia_hora
# NULL

In [74]:
dataframe.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

In [76]:
dataframe.loc[dataframe.ocorrencia_aerodromo == '****', ['ocorrencia_aerodromo']] = pd.NA

In [77]:
dataframe

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6109,80245,80245,80245,80245,80245,INCIDENTE,-8.12638,-34.92277,RECIFE,PE,...,2021-08-15,15:05:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6110,80247,80247,80247,80247,80247,INCIDENTE,-8.713611111111,-63.90277777777,PORTO VELHO,RO,...,2021-08-16,02:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6111,80251,80251,80251,80251,80251,INCIDENTE,-1.384722222222,-48.47888888888,BELÉM,PA,...,2021-08-17,15:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6112,80257,80257,80257,80257,80257,ACIDENTE,-15.430833,-54.699722,DOM AQUINO,MT,...,2021-08-18,16:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6113,80259,80259,80259,80259,80259,INCIDENTE,-23.00694444444,-47.13444444444,CAMPINAS,SP,...,2021-08-18,12:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [88]:
dataframe.loc[:, ['codigo_ocorrencia','ocorrencia_aerodromo']]

      codigo_ocorrencia ocorrencia_aerodromo
0                 40211                 <NA>
1                 40349                 SBBE
2                 40351                 SBRJ
3                 39527                 <NA>
4                 40324                 SBPK
...                 ...                  ...
6109              80245                 SBRF
6110              80247                 SBPV
6111              80251                 SBBE
6112              80257                 <NA>
6113              80259                 SBKP

[6114 rows x 2 columns]

In [11]:
dataframe.replace(['**','###!','####','****', '*****', 'NULL'], pd.NA, inplace=True)

In [13]:
dataframe.isna().sum()

codigo_ocorrencia                    0
codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude                  4
ocorrencia_longitude                 5
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo              2456
ocorrencia_dia                       0
ocorrencia_hora                      0
investigacao_aeronave_liberada       0
investigacao_status                  0
divulgacao_relatorio_numero          7
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao            0
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

In [15]:
dataframe.isnull().sum()

codigo_ocorrencia                    0
codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude                  4
ocorrencia_longitude                 5
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo              2456
ocorrencia_dia                       0
ocorrencia_hora                      0
investigacao_aeronave_liberada       0
investigacao_status                  0
divulgacao_relatorio_numero          7
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao            0
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

In [112]:
dataframe.loc[40211]

codigo_ocorrencia1                              40211
codigo_ocorrencia2                              40211
codigo_ocorrencia3                              40211
codigo_ocorrencia4                              40211
ocorrencia_classificacao                    INCIDENTE
ocorrencia_latitude                               ***
ocorrencia_longitude                              ***
ocorrencia_cidade                      RIO DE JANEIRO
ocorrencia_uf                                      RJ
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                                0
ocorrencia_dia                    2010-01-03 00:00:00
ocorrencia_hora                              12:00:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero                       ***
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                           0
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 40211, dtype: object

In [7]:
dataframe.loc[:, ['codigo_ocorrencia','ocorrencia_aerodromo']]

      codigo_ocorrencia ocorrencia_aerodromo
0                 40211                 ****
1                 40349                 SBBE
2                 40351                 SBRJ
3                 39527                 ****
4                 40324                 SBPK
...                 ...                  ...
6109              80245                 SBRF
6110              80247                 SBPV
6111              80251                 SBBE
6112              80257                 ****
6113              80259                 SBKP

[6114 rows x 2 columns]

In [16]:
dataframe.isna().sum()

codigo_ocorrencia                    0
codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude                  4
ocorrencia_longitude                 5
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo              2456
ocorrencia_dia                       0
ocorrencia_hora                      0
investigacao_aeronave_liberada       0
investigacao_status                  0
divulgacao_relatorio_numero          7
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao            0
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

In [10]:
dataframe.fillna(0, inplace=True)

In [100]:
dataframe.loc[:, ['codigo_ocorrencia','ocorrencia_aerodromo']]

      codigo_ocorrencia ocorrencia_aerodromo
0                 40211                    0
1                 40349                 SBBE
2                 40351                 SBRJ
3                 39527                    0
4                 40324                 SBPK
...                 ...                  ...
6109              80245                 SBRF
6110              80247                 SBPV
6111              80251                 SBBE
6112              80257                    0
6113              80259                 SBKP

[6114 rows x 2 columns]

In [ ]:
dataframe.fillna(value{'total_recomendacoes':10}, inplace=True)

In [ ]:
dataframe.isnull().sum()

In [6]:
dataframe['total_recomendacoes_bkp'] = dataframe.total_recomendacoes

In [7]:
dataframe.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,total_recomendacoes_bkp
0,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,0
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,0
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,0
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO,0
4,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,0

In [9]:
dataframe.drop(['total_recomendacoes_bkp'], axis=1, inplace=True)

In [ ]:
dataframe.dropna(subset=['ocorrencia_uf'])

In [ ]:
dataframe.dop_duplicate(inplace=True)

In [ ]:
dataframe